# -*- coding: utf-8 -*-
"""SIF2500252.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15_Z4kiqSVeP_6PzB8XcSi6Fmk55T5a7Y
"""

name=input("What is your name? ").title()
Total_classes=int(input("How many classes were held? "))
Classes_attended=int(input("How many classes did you attend? "))
percentage=(Classes_attended/Total_classes)*100
print(name,"your attendence percentage is",round(percentage,2),"%")

if percentage >=75:
 print("You are allowed to sit in exam")
else:
 print("You are not allowed to sit in exam")